### ISSUE TITLE
openmldb-tool-test: fails eaily 

### ISSUE THREAD

**Issue by aceforeverd** [4paradigm/OpenMLDB#3406] opened 2023-07-28 13:26 UTC
I run in latest main, fails easily, https://github.com/4paradigm/OpenMLDB/actions/runs/5691660219/job/15427258786

**Comment by vagetablechicken** [comment] 2023-07-31 09:16
@lqy222 has checked about it, is it easy to fix?

**Comment by lqy222** [comment] 2023-08-07 04:33
fixed in  https://github.com/4paradigm/OpenMLDB/pull/3283 , caused by wrong assert

**Closed as completed** 2023-09-18 03:10 UTC
Labels: bug, tools
