### ISSUE TITLE
Fail to resolve expression: ifnull(null, default)

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#2301] opened 2022-08-04 11:39 UTC
```
127.0.0.1:7527/db> SELECT ifnull(NULL, "default");
Error: no tablet available for sqlFail to resolve expression: ifnull(null, default)
```
The example in udf is fail.
Test on

**Comment by aceforeverd** [comment] 2022-08-04 11:48
Implementation limitation to current the function resolving: 
> expr must has the same type with default

`NULL` is a null type different with `"default"` (string type). So unable to resolve function `ifnull(nullable null, string)`. 

Document update needed

**Comment by aceforeverd** [comment] 2022-08-04 11:50
write 
```sql
select ifnull(cast(null as string), "default")
```

**Comment by lumianph** [comment] 2023-03-26 07:11
the issue is not fully resolved, only the document is addressed

**Comment by aceforeverd** [comment] 2023-03-27 02:23
Already resolved in #3030 as the fix to #2895 (compatible type for Cond like exprs).

**Closed as completed** 2023-03-27 03:35 UTC
Labels: documentation, execute-engine

**Comment by aceforeverd** [comment] 2023-03-27 03:38
user no long need explicit cast since v0.7.2

> write
> 
> ```sql
> select ifnull(cast(null as string), "default")
> ```

**Comment by vagetablechicken** [comment] 2023-03-27 04:33
> user no long need explicit cast since v0.7.2
> 
> > write
> > ```sql
> > select ifnull(cast(null as string), "default")
> > ```

so https://github.com/4paradigm/OpenMLDB/blob/1503383469ef2ed45f794e27ab1e1f9e96c727bf/hybridse/src/udf/default_udf_library.cc#L1989 need update?
